project:
  type: website
  render:
    - index.qmd
    - session_1/session_1_SOLUTIONS.Rmd
    - session_2/xgboost_shap_workflow_tutorial.Rmd
  output-dir: _site

website:
  title: "EDAM September Training"
  favicon: images/edam-logo.png
  navbar:
    background: "#0A3B81"
    type: dark
    logo: images/edam-logo.png
    left:
      - href: index.qmd
        text: Home
      - href: session_1/session_1_SOLUTIONS.Rmd
        text: "Session 1: cleaning and exporing data"
      - href: session_2/xgboost_shap_workflow_tutorial.Rmd
        text: "Session 2: creating an exAI pipeline"

format:
  html:
    theme: [flatly, custom.scss]
    toc: true
    code-fold: show
